name: course_gnome
description: Discover college courses and plan your schedule with Course Gnome.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^0.21.0

  # url_launcher: ^4.0.2
  # font_awesome_flutter: ^8.2.0

  # firebase_core: ^0.3.1+1
  # google_sign_in: ^3.0.4
  
  # color: ^2.1.1
  # meta: ^1.1.6

  firebase: ^5.0.4
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  bloc: ^0.15.0
  equatable: ^0.5.1
  algolia: ^0.1.6+1
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  json_serializable: ^3.2.2
  pedantic: ^1.8.0+1

flutter_icons:
  android: true
  ios: true
  image_path_android: "../core/assets/icons/android.png"
  image_path_ios: "../core/assets/icons/ios.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - packages/core/assets/images/logo.png
    - assets/images/
  #    - packages/core/assets/images/algolia

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
