name: course_gnome
description: Discover college courses and plan your schedule with Course Gnome.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  course_gnome_data: 
    path: ../course_gnome_data
  flutter_bloc: ^0.21.0
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  bloc: ^0.15.0
  equatable: ^0.5.1
  algolia: ^0.1.6+1
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  json_serializable: ^3.2.2
  pedantic: ^1.7.0
  migrate_to_web: 
    path: ../../Flutter/migrate_to_web

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/android.png"
  image_path_ios: "assets/icons/ios.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
