name: course_gnome_mobile
description: Discover college courses and plan your schedule with Course Gnome.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^0.10.0

  url_launcher: ^4.0.2
  shared_preferences: ^0.4.3
  font_awesome_flutter: ^8.2.0
  
  firebase_core: ^0.3.1+1
  google_sign_in: ^3.0.4

  auto_size_text: ^0.3.0

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "../core/assets/icons/android.png"
  image_path_ios: "../core/assets/icons/ios.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - packages/core/assets/images/logo.png
#    - packages/core/assets/images/algolia

  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Regular.ttf
    - asset: assets/fonts/Lato-Light.ttf
      weight: 300
    - asset: assets/fonts/Lato-Bold.ttf
      weight: 700
  - family: Merriweather
    fonts:
    - asset: assets/fonts/Merriweather-Regular.ttf
