name: course_gnome_mobile
description: Discover college courses and plan your schedule with Course Gnome.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^4.0.2
  shared_preferences: ^0.4.3
  cloud_functions: ^0.0.5
  font_awesome_flutter: ^8.2.0
  
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.2
  cloud_firestore: ^0.9.7
  google_sign_in: ^3.0.4
#  firebase_analytics: ^1.0.6

  auto_size_text: ^0.3.0

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon-android.png"
  image_path_ios: "assets/icons/icon-ios.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icon.png
    - assets/images/

  fonts:
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Regular.ttf
    - asset: assets/fonts/Lato-Light.ttf
      weight: 300
    - asset: assets/fonts/Lato-Bold.ttf
      weight: 700
