name: core
description: Shared code for mobile and web Course Gnome apps.
environment:
  sdk: '>=2.0.0 <3.0.0'
#  flutter: ^0.1.2
dependencies:
  http: ^0.12.0+1
#  firebase:
#    path: ../../firebase-dart