name: core
description: Shared code for mobile and web Course Gnome apps.
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: ^0.12.0+1
  color: ^2.1.1
  meta: ^1.1.6
  bloc: ^0.11.2
  equatable: ^0.1.10
  algolia: ^0.1.6+1
  json_annotation: ^2.0.0
dev_dependencies:
  test: ^1.5.3
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  pedantic: ^1.5.0
