name: core
description: Shared code for mobile and web Course Gnome apps.
environment:
  sdk: '>=2.1.0 <3.0.0'
#  flutter: ^0.1.2
dependencies:
  http: ^0.12.0+1
  color: ^2.1.1
  meta: ^1.1.7
  bloc: ^0.9.0
  equatable: ^0.1.10
  algolia: 0.1.4+1
#  firebase:
#    path: ../../firebase-dart