final Map departments = <String, String>{
  'ACA': 'Academy for Classical Acting',
  'ACCY': 'Accountancy',
  'AMST': 'American Studies',
  'ANAT': 'Anatomy &amp; Regenerative Biology',
  'ANTH': 'Anthropology',
  'APSC': 'Applied Science',
  'ARAB': 'Arabic',
  'AH': 'Art/Art History',
  'FA': 'Art/Fine Arts',
  'ASTR': 'Astronomy',
  'BIOC': 'Biochemistry',
  'BISC': 'Biological Sciences',
  'BME': 'Biomedical Engineering',
  'BMSC': 'Biomedical Sciences',
  'BIOS': 'Biostatistics',
  'BADM': 'Business Administration',
  'CANC': 'Cancer Biology',
  'CHEM': 'Chemistry',
  'CHIN': 'Chinese',
  'CE': 'Civil Engineering',
  'CLAS': 'Classical Studies',
  'CCAS': 'Columbian College',
  'COMM': 'Communication',
  'CSCI': 'Computer Science',
  'CAH': 'Corcoran Art History',
  'CCE': 'Corcoran Continuing Education',
  'CFA': 'Corcoran Fine Art',
  'CFN': 'Corcoran First Year Foundation',
  'CGD': 'Corcoran Graphic Design',
  'CPH': 'Corcoran Photography',
  'CPJ': 'Corcoran Photojournalism',
  'CNSL': 'Counseling',
  'CPED': 'Curriculum and Pedagogy',
  'DATS': 'Data Science',
  'DNSC': 'Decision Sciences',
  'EALL': 'East Asian Lang &amp; Lit',
  'ECON': 'Economics',
  'EDUC': 'Educational Leadership',
  'ECE': 'Electrical &amp; Computer Engring',
  'EHS': 'Emergency Health Services',
  'ENGL': 'English',
  'EAP': 'English for Academic Purposes',
  'EMSE': 'Engr Mgt &amp; Systems Engineering',
  'ENRP': 'Environmental Resource Policy',
  'ENVR': 'Environmental Studies',
  'EPID': 'Epidemiology',
  'EXNS': 'Exercise &amp; Nutrition Sciences',
  'FILM': 'Film Studies',
  'FINA': 'Finance',
  'FORS': 'Forensic Sciences',
  'FREN': 'French',
  'GTCH': 'GWTeach',
  'GENO': 'Genomics and Bioinformatics',
  'GEOG': 'Geography',
  'GEOL': 'Geology',
  'GER': 'Germanic Language &amp; Literature',
  'GCON': 'Government Contracts',
  'SEHD': 'Graduate School of Ed &amp; HD',
  'GREK': 'Greek',
  'HSCI': 'Health Sciences Programs',
  'HLWL': 'Health and Wellness',
  'HSML': 'HealthServicesMgt&amp;Leadership',
  'HEBR': 'Hebrew',
  'HIST': 'History',
  'HOMP': 'Hominid Paleobiology',
  'HONR': 'Honors',
  'HOL': 'Human Organizational Learning',
  'HSSJ': 'Human Services&amp;Social Justice',
  'ISTM': 'InfSystemsTechnologyManagement',
  'IDIS': 'Interdisciplinary Courses',
  'IA': 'Interior Architecture',
  'IAFF': 'International Affairs',
  'IBUS': 'International Business',
  'ITAL': 'Italian',
  'JAPN': 'Japanese',
  'JSTD': 'Judaic Studies',
  'KOR': 'Korean',
  'LATN': 'Latin',
  'LSPA': 'Lifestyle,Sport&amp; Phys Activity',
  'LING': 'Linguistics',
  'MGT': 'Management',
  'MKTG': 'Marketing',
  'MBAD': 'Master of Business Administrtn',
  'MATH': 'Mathematics',
  'MAE': 'Mechanical &amp; Aerospace Engring',
  'MICR': 'Microbio, Immun &amp; Tropical Med',
  'MMED': 'Molecular Medicine',
  'MUS': 'Music',
  'NSC': 'Naval Science',
  'NRSC': 'Neuroscience',
  'ORSC': 'Organizational Sciences',
  'PATH': 'Pathology',
  'PSTD': 'Peace Studies',
  'PERS': 'Persian',
  'PHAR': 'Pharmacology',
  'PHIL': 'Philosophy',
  'PT': 'Physical Therapy',
  'PA': 'Physician Assistant',
  'PHYS': 'Physics',
  'PHYL': 'Physiology',
  'PMGT': 'Political Management',
  'PPSY': 'Political Psychology',
  'PSC': 'Political Science',
  'PSYD': 'Professional Psychology',
  'PSYC': 'Psychology',
  'PUBH': 'Public Health',
  'PPPA': 'Public Policy and Public Admin',
  'REL': 'Religion',
  'SEAS': 'School of Eng &amp; Applied Sci',
  'SMPA': 'School of Media&amp;Public Affairs',
  'SLAV': 'Slavic Languages &amp; Lit',
  'SOC': 'Sociology',
  'SPAN': 'Spanish',
  'SPED': 'Special Education',
  'SPHR': 'Speech, Lang., &amp; Hearing Sci.',
  'STAT': 'Statistics',
  'SMPP': 'Strategic Mgt &amp; Public Policy',
  'SUST': 'Sustainability',
  'TSAP': 'Teaching in Sci. &amp; Professions',
  'TRDA': 'Theatre and Dance',
  'TSTD': 'Tourism Studies',
  'UW': 'University Writing',
  'WLP': 'Women and Leadership Program',
  'WGSS': 'Women\'s,Gender&amp;SexualityStudy',
};
